---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3
      - python3-pip
      - git
      - curl
      - unzip
  when: ansible_os_family == "Debian"

- name: Create application directory
  file:
    path: /opt/flask-app
    state: directory
    mode: '0755' 